services:
  nginx:
    image: nginx
    ports:
      - "8081:80"
    networks:
      - dblink
      - traefik1
  apache:
    image: httpd
    ports:
      - "8082:80"
    networks:
      - traefik2
  mySQL:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "8083:80"
    networks:
      - dblink
      - traefik3
    volumes:
      - dbpersistance:/persistance
  redis:
    image: redis
    ports:
      - "8084:80"
    networks:
      - traefik4
  mongoDB:
    image: mongo
    ports:
      - "8085:80"
    volumes:
      - dbpersistance:/persistance
    networks:
      - traefik5
  flaskapp:
    build: 
      context: "./"
      dockerfile: "flask.dockerfile"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    ports:
      - "8090:80"
    networks:
      - traefik6

networks:
  traefik1:
  traefik2:
  traefik3:
  traefik4:
  traefik5:
  traefik6:
  dblink:

volumes:
  dbpersistance: