services:
  nginx:
    image: nginx
    ports:
      - "8081:80"
    networks:
      - dblink
  apache:
    image: httpd
    ports:
      - "8082:80"
  mySQL:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "8083:80"
    networks:
      - dblink
    volumes:
      - dbpersistance
  redis:
    image: redis
    ports:
      - "8084:80"
  mongoDB:
    image: mongo
    ports:
      - "8085:80"
    volumes:
      - dbpersistance
  flaskapp:
    build: flask.dockerfile
    ports:
      - "8090:80"

networks:
  dblink:

volumes:
  dbpersistance: